#!/bin/bash
# Deploy FinOps AI to GitHub Pages or any static host

echo "FinOps AI Deployment Script"
echo "==========================="
echo ""
echo "Option 1: Deploy to GitHub Pages"
echo "--------------------------------"
echo "1. Create a new GitHub repository (e.g., finops-ai-demo)"
echo "2. Run these commands:"
echo ""
echo "   cd ~/.openclaw/workspace/finops-ai"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/finops-ai-demo.git"
echo "   git push -u origin main"
echo ""
echo "3. Go to GitHub repo → Settings → Pages"
echo "4. Select 'Deploy from a branch' → 'main' → '/out' folder"
echo "5. Your site will be at: https://YOUR_USERNAME.github.io/finops-ai-demo"
echo ""
echo "Option 2: Deploy to Netlify (Drag & Drop)"
echo "-----------------------------------------"
echo "1. Go to https://app.netlify.com/drop"
echo "2. Drag the 'out' folder from: ~/.openclaw/workspace/finops-ai/out"
echo "3. Get instant URL like: https://unique-name.netlify.app"
echo ""
echo "Option 3: Deploy to Vercel"
echo "--------------------------"
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Login: vercel login"
echo "3. Deploy: cd ~/.openclaw/workspace/finops-ai && vercel --prod"
echo ""
echo "Files are ready at: ~/.openclaw/workspace/finops-ai/out/"
echo ""